### ISSUE TITLE
Add Voicemeeter support

### ISSUE THREAD

**Issue by DrSakuu** [Raphiiko/OyasumiVR#124]
Voicemeeter has an API to control it remotely https://download.vb-audio.com/Download_CABLE/VoicemeeterRemoteAPI.pdf, this would allow the muting of game sounds like VRChat while keeping sleeping/alarm sounds from browser or music player, if the user has set up Voicemeeter that way. For my specific setup, I can't control the volume of my Quest 2 via Virtual Desktop with the Windows sound settings, because VD mirrors the signal sent to its virtual audio device and ignores its volume or muted state. Controlling Voicemeeter directly is the only way to turn off sounds for me.

**Comment by Raphiiko** [comment]
I've looked into adding support for it in the past, but my main issue with doing so is that Voicemeeter isn't the only widely used option out there. For example I've got friends who use Steelseries' Sonar, and I personally am a user of Elgato's Wave Link. 

Being the only person working on this project, implementing support for every virtual audio mixer under the sun just isn't workable for me, especially when I can use that time to ship other features that have a wider impact. I'd rather avoid spending time on adding features that I personally won't use and are otherwise very specific to only a few users. Things would be a lot simpler if VD would just add an option to respect Windows' audio settings. 

What I can do, assuming you are able to do some scripting of your own, is point you in the right direction:

**Getting the current sleep mode:**

A proper API for OyasumiVR is still planned for some time in the future, but there's already a few ways you can get the current sleep mode:

1. Via OSCQuery:
    1. Discover OyasumiVR's OSCQuery server port via Zeroconf/MDNS (named `OyasumiVR` of type `_oscjson._tcp.local`)
    2. In your script, poll `http://127.0.0.1:port/OyasumiVR/SleepMode` periodically to check the current sleep mode
2. Via MQTT
    1. Setup a MQTT broker like Mosquitto
    2. Configure and enable the Home Assistant integration in OyasumiVR to connect it to your broker
    3. In your script, connect to the same broker. You'll find the sleep mode to be published at `OyasumiVR/sleepMode/state`, which is updated in real time.
3. Reading OyasumiVR's settings file
    1. The file is located at `%appdata%/co.raphii.oyasumi/settings.dat`. The contents are in JSON. Within, you'll find the current sleep mode on the `SLEEP_MODE` property.
    2. In your script, periodically read this file to check the current sleep mode.

At this point, just grab whatever voicemeeter api wrapper exists for your chosen language, and script to do whatever you want voicemeeter to do in response to OyasumiVR's sleep mode changing.

**Comment by Raphiiko** [comment]
For you and other people who might have a similar issue, another user currently solves it by using [Voicemeeter Windows Volume](https://github.com/Frosthaven/voicemeeter-windows-volume), and using it to sync the volume on the channel for VRChat, to the volume of the virtual windows audio device, which can then be controlled by OyasumiVR.
