### ISSUE TITLE
automatic side sleep does not work on uploaded avatar

### ISSUE THREAD

**Issue by alzahhar3** [Raphiiko/OyasumiVR#39]
weird issue, I am using latest gogo loco, side sleep works on test avatar, but once I upload it it does not change my position, only lock and unlocks feet.

**Comment by Raphiiko** [comment]
If only the foot lock works, it sounds to me like there's a possibility that the required parameter gets renamed by VRCFury. This is because unlike the pose parameter, the foot lock parameter is defined as a global variable in VRCFury's GogoLoco prefab. 

Are you using VRCFury to install GogoLoco, and if so, are you sure you're using the VRCFury workaround? https://github.com/Raphiiko/OyasumiVR/wiki/Workarounds-for-GoGo-Loco

By default, VRCFury renames the parameter GoGoLoco uses to control your pose. You can verify this by turning on the avatar debug view ingame and checking the list of parameters.

**Comment by alzahhar3** [comment]
Oh I did not realize that was the reason. Yes I am using VRCFury. I tried this fix and it worked, thanks a lot you are so helpful <3
