### ISSUE TITLE
Can't change OSC port

### ISSUE THREAD

**Issue by oniyakun** [Raphiiko/OyasumiVR#71]
I manually changed VRChat's osc port, but now the problem is that I can't find any Settings in OyasumiVR to change the osc port, which seems to have been removed since version 11.0? I can't use anything that requires osc now.

**Comment by Raphiiko** [comment]
Correct, I see the problem. The reason that this is no longer possible, is because OyasumiVR now automatically discovers VRChat's OSC server via OSCQuery. This is generally how OSCQuery is meant to work: various applications are able to discover each other without knowing each others ports and addresses in advance. 

I've now tried changing the port through the launch parameter myself as well, and it turns out that VRChat's implementation of this is kind of a half-measure: When changing the port away from the default port (9000), VRChat keeps advertising port 9000 over OSCQuery, even though this is no longer correct. It looks to me like they have just hardcoded this value. ...I would personally consider this a bug in VRChat, not OyasumiVR. 

I've submitted a bug report with VRChat, as this is something that should be fixed on their side: https://feedback.vrchat.com/bug-reports/p/oscquery-vrchat-reports-the-incorrect-listening-port-for-osc-when-changing-it-vi. If you could give it an upvote that would be appreciated. 

In the meantime that of course is of no use to you, so I'll see if I can add some flags to OyasumiVR to override whatever port VRChat advertises. Until I get that feature out, your only option is to leave VRChat running on its default port 9000.

**Comment by Raphiiko** [comment]
![image](https://github.com/Raphiiko/OyasumiVR/assets/111654848/f7485f81-1f14-4cea-8ecb-eeb55178a956)

I didn't get to adding the port overrides, but it seems like VChat has fixed this issue now in their new beta build `2024.1.1`, build `1400`. I'm sure it will make its way to the release version soon. As such, I'll be closing this issue.
